#!/usr/bin/env python3
"""
BindMaster — unified CLI entry point (system Python, stdlib only)

Dispatches sub-commands to their respective scripts:
  (no args) → interactive TUI menu (tui/app.py)
  install   → bash install/install.sh (or install_aarch.sh on aarch64)
  configure → python configurator/configurator.py
  evaluate  → conda run -n binder-eval binder-compare (Evaluator/binder_comparison)

Usage:
  bindmaster                                                    Interactive menu (TUI)
  bindmaster install   [--tool bindcraft|boltzgen|mosaic|all] [--cuda VERSION] [--skip-examples]
  bindmaster configure [options passed through to configurator.py]
  bindmaster evaluate  <binder-compare args>   (e.g. run --mosaic DIR --target-seq SEQ -o OUT)
  bindmaster --help
"""

import os
import platform
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent

BOLD = "\033[1m"
CYAN = "\033[0;36m"
GREEN = "\033[0;32m"
RED = "\033[0;31m"
RESET = "\033[0m"

USAGE = f"""{BOLD}BindMaster{RESET} — GPU-accelerated protein binder design toolkit

{BOLD}Usage:{RESET}
  bindmaster                                                    Interactive menu (TUI)
  bindmaster install   [--tool bindcraft|boltzgen|mosaic|all] [--cuda VERSION] [--skip-examples]
  bindmaster configure [options passed through]
  bindmaster evaluate  <binder-compare args>   (e.g. run --mosaic DIR --target-seq SEQ -o OUT)
  bindmaster --help

{BOLD}Commands:{RESET}
  {CYAN}(no args){RESET}  Launch interactive menu — install, configure, run, evaluate
  {CYAN}install{RESET}    Install BindCraft, BoltzGen, and/or Mosaic
  {CYAN}configure{RESET}  Interactive wizard to set up a run (target, tools, parameters)
  {CYAN}evaluate{RESET}   Passthrough to the binder-compare evaluator (extract / refold / report / run)

{BOLD}Environments:{RESET}
  install    → bash          {REPO}/install/install.sh  (install_aarch.sh on aarch64)
  configure  → system python {REPO}/configurator/configurator.py
  evaluate   → conda env binder-eval → binder-compare (Evaluator/binder_comparison)

{BOLD}Clone:{RESET}
  git clone https://github.com/damborik22/BinderScout.git
  # `install` auto-selects install_aarch.sh on aarch64 (DGX Spark / Grace-Hopper).
"""


def _install_bindmaster_shortcut() -> None:
    """Write BindMaster/bin/bindmaster pointing at this script (idempotent)."""
    local_bin = REPO / "bin"
    script = Path(__file__).resolve()
    target_line = f'exec python3 "{script}" "$@"\n'
    shortcut_content = f"#!/usr/bin/env bash\n# BindMaster shortcut — auto-generated by bindmaster.py\n{target_line}"

    # Primary: BindMaster/bin/ (always writable, fully local)
    local_bin.mkdir(exist_ok=True)
    shortcut = local_bin / "bindmaster"
    if not shortcut.exists() or target_line not in shortcut.read_text():
        shortcut.write_text(shortcut_content)
        shortcut.chmod(0o755)
        print(f"{GREEN}✓{RESET} Shortcut installed: {shortcut}")

    # Secondary: ~/.local/bin/ (convenience, non-fatal if not writable)
    try:
        home_bin = Path.home() / ".local" / "bin"
        home_bin.mkdir(parents=True, exist_ok=True)
        home_shortcut = home_bin / "bindmaster"
        if not home_shortcut.exists() or target_line not in home_shortcut.read_text():
            home_shortcut.write_text(shortcut_content)
            home_shortcut.chmod(0o755)
    except OSError:
        pass  # ~/.local/bin not writable — BindMaster/bin/ is the primary location


def _find_conda_base() -> Path | None:
    """Return the conda base dir (local standalone install first, then system)."""
    local = REPO / "conda"
    candidates = [
        local,
        Path.home() / "miniforge3",
        Path.home() / "mambaforge",
        Path.home() / "miniconda3",
        Path.home() / "anaconda3",
        Path("/opt/conda"),
        Path("/opt/miniforge3"),
    ]
    for base in candidates:
        if (base / "etc" / "profile.d" / "conda.sh").exists() and (base / "bin" / "conda").exists():
            return base
    return None


def _dispatch(cmd: str, args: list) -> None:
    """Resolve and exec the appropriate sub-command. Never returns."""
    if cmd == "install":
        # Pick the installer for THIS machine. Without this, `bindmaster install` on a
        # DGX Spark ran the x86_64 script: CUDA defaulting to 12.4 instead of 13.0,
        # conda asked for pytorch-cuda=12.4 and gcc_linux-64 (no linux-aarch64 builds),
        # and none of the aarch64 patches applied. install.sh warned but proceeded.
        name = "install_aarch.sh" if platform.machine() == "aarch64" else "install.sh"
        script = REPO / "install" / name
        if not script.exists():
            print(f"{RED}✗ {name} not found: {script}{RESET}", file=sys.stderr)
            sys.exit(1)
        print(f"{BOLD}BindMaster → install{RESET}  ({platform.machine()} → {name})")
        os.execv("/bin/bash", ["/bin/bash", str(script)] + args)

    elif cmd == "configure":
        script = REPO / "configurator" / "configurator.py"
        if not script.exists():
            print(f"{RED}✗ configurator.py not found: {script}{RESET}", file=sys.stderr)
            sys.exit(1)
        print(f"{BOLD}BindMaster → configure{RESET}")
        os.execv(sys.executable, [sys.executable, str(script)] + args)

    elif cmd == "evaluate":
        conda_base = _find_conda_base()
        if conda_base is None:
            print(
                f"{RED}✗ conda not found — install the evaluator first (`bindmaster install --tool all`){RESET}",
                file=sys.stderr,
            )
            sys.exit(1)
        conda_bin = conda_base / "bin" / "conda"
        print(f"{BOLD}BindMaster → evaluate (binder-compare){RESET}")
        os.execv(
            str(conda_bin),
            [str(conda_bin), "run", "-n", "binder-eval", "--no-capture-output", "binder-compare"] + args,
        )

    else:
        print(f"{RED}✗ Unknown command: {cmd!r}{RESET}", file=sys.stderr)
        print(USAGE, file=sys.stderr)
        sys.exit(1)


def main() -> None:
    _install_bindmaster_shortcut()

    args = sys.argv[1:]

    if not args:
        from tui.app import launch_tui

        launch_tui(REPO)
        return

    if args[0] in ("-h", "--help"):
        print(USAGE)
        sys.exit(0)

    cmd, rest = args[0], args[1:]
    _dispatch(cmd, rest)


if __name__ == "__main__":
    main()
