#!/usr/bin/env python3
"""
BindMaster — unified CLI entry point (system Python, stdlib only)

Dispatches sub-commands to their respective scripts:
  install   → bash install/install.sh
  configure → python configurator/configurator.py
  evaluate  → Mosaic/.venv/bin/python evaluator/evaluator.py

Usage:
  bindmaster install   [--tool bindcraft|boltzgen|mosaic|all] [--cuda VERSION] [--skip-examples]
  bindmaster configure [options passed through to configurator.py]
  bindmaster evaluate  <run-dir> [--metric METRIC] [--top N] [--refold N]
  bindmaster --help
"""

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
MOSAIC_VENV_PYTHON = REPO / "Mosaic" / ".venv" / "bin" / "python"

BOLD  = "\033[1m"
CYAN  = "\033[0;36m"
GREEN = "\033[0;32m"
RED   = "\033[0;31m"
RESET = "\033[0m"

USAGE = f"""{BOLD}BindMaster{RESET} — GPU-accelerated protein binder design toolkit

{BOLD}Usage:{RESET}
  bindmaster install   [--tool bindcraft|boltzgen|mosaic|all] [--cuda VERSION] [--skip-examples]
  bindmaster configure [options passed through]
  bindmaster evaluate  <run-dir> [--metric METRIC] [--top N] [--refold N]
  bindmaster --help

{BOLD}Commands:{RESET}
  {CYAN}install{RESET}    Install BindCraft, BoltzGen, and/or Mosaic
  {CYAN}configure{RESET}  Interactive wizard to set up a run (target, tools, parameters)
  {CYAN}evaluate{RESET}   Parse outputs, rank designs, optionally re-fold top candidates

{BOLD}Environments:{RESET}
  install    → bash          {REPO}/install/install.sh
  configure  → system python {REPO}/configurator/configurator.py
  evaluate   → Mosaic venv   {REPO}/evaluator/evaluator.py

{BOLD}Clone:{RESET}
  # x86_64 (default)
  git clone https://github.com/damborik22/BindMaster.git
  # aarch64 / DGX Spark
  git clone -b aarch64 https://github.com/damborik22/BindMaster.git
"""


def _install_bindmaster_shortcut() -> None:
    """Write ~/.local/bin/bindmaster pointing at this script (idempotent)."""
    shortcuts_dir = Path.home() / ".local" / "bin"
    shortcut = shortcuts_dir / "bindmaster"
    script = Path(__file__).resolve()
    target_line = f'exec python3 "{script}" "$@"\n'

    if shortcut.exists():
        try:
            if target_line in shortcut.read_text():
                return  # already up to date
        except OSError:
            pass

    shortcuts_dir.mkdir(parents=True, exist_ok=True)
    shortcut.write_text(
        "#!/usr/bin/env bash\n"
        "# BindMaster shortcut — auto-generated by bindmaster.py\n"
        f"{target_line}"
    )
    shortcut.chmod(0o755)
    print(f"{GREEN}✓{RESET} Shortcut installed: {shortcut}")


def _dispatch(cmd: str, args: list) -> None:
    """Resolve and exec the appropriate sub-command. Never returns."""
    if cmd == "install":
        script = REPO / "install" / "install.sh"
        if not script.exists():
            print(f"{RED}✗ install.sh not found: {script}{RESET}", file=sys.stderr)
            sys.exit(1)
        print(f"{BOLD}BindMaster → install{RESET}")
        os.execv("/bin/bash", ["/bin/bash", str(script)] + args)

    elif cmd == "configure":
        script = REPO / "configurator" / "configurator.py"
        if not script.exists():
            print(f"{RED}✗ configurator.py not found: {script}{RESET}", file=sys.stderr)
            sys.exit(1)
        print(f"{BOLD}BindMaster → configure{RESET}")
        os.execv(sys.executable, [sys.executable, str(script)] + args)

    elif cmd == "evaluate":
        if not MOSAIC_VENV_PYTHON.exists():
            print(
                f"{RED}✗ Mosaic must be installed first "
                f"(`bindmaster install --tool mosaic`){RESET}",
                file=sys.stderr,
            )
            sys.exit(1)
        script = REPO / "evaluator" / "evaluator.py"
        if not script.exists():
            print(f"{RED}✗ evaluator.py not found: {script}{RESET}", file=sys.stderr)
            sys.exit(1)
        print(f"{BOLD}BindMaster → evaluate{RESET}")
        os.execv(str(MOSAIC_VENV_PYTHON), [str(MOSAIC_VENV_PYTHON), str(script)] + args)

    else:
        print(f"{RED}✗ Unknown command: {cmd!r}{RESET}", file=sys.stderr)
        print(USAGE, file=sys.stderr)
        sys.exit(1)


def main() -> None:
    _install_bindmaster_shortcut()

    args = sys.argv[1:]
    if not args or args[0] in ("-h", "--help"):
        print(USAGE)
        sys.exit(0)

    cmd, rest = args[0], args[1:]
    _dispatch(cmd, rest)


if __name__ == "__main__":
    main()
